version: '3.4'

services:
  app:
    build: .
    volumes:
        - ./:/app:delegated
    working_dir: /app
    depends_on:
      - db

  db:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
