version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
        - ./:/app:delegated
    working_dir: /app
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
