version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
        - ./:/app:delegated
    working_dir: /app
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306

  mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
