name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-step1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: nasjp/parabase:latest
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile-app
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: mysql/5.7.34
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile-mysql
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - run: COMPOSE_DOCKER_CLI_BUILD=1 make test
